server:
  port: 8101

eureka:
  instance:
    hostname: eurekaone
  client:
    # 表示不向注册中心注册自己
    register-with-eureka: false
    # 是否检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eurekatwo.com:8102/eureka/
  server:
    # 关闭自我保护模式，保证不可用服务被及时删除
    enable-self-preservation: false
    # server清理无效节点的时间间隔
    eviction-interval-timer-in-ms: 2000
