server:
  port: 8001

spring:
  application:
    name: order

  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  #采样率值介于0-1之间,1标识全部采集

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka
ribbon:
  read-time-out: 5000
  connection-time-out: 5000
logging:
  level:
    example.order.service.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true