server:
  port: 8001

spring:
  application:
    name: order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka
ribbon:
  read-time-out: 5000
  connection-time-out: 5000
logging:
  level:
    example.order.service.PaymentFeignService: debug
